README.md
The example using `getClientRects()` was using the returned value as if it were a single `DOMRect` object. However, [getClientRects()][1] returns a list for `DOMRect` objects.
This commit fixes the example by instead using [getBoundingClientRect()][2], which _does_ return a single `DOMRect` object.
[1]: https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects
[2]: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
=> docs: fix typo in `README.md`

README.md
Only the service worker and web worker scripts have to be hosted on the HTML page's origin. All other scripts can be hosted on other origins.
=> Clarify hosting requirements for static assets

src/react/script.tsx
This script is being placed in the head of my application it adds the `data-pt-script` attribute to the script tag *BEFORE* React has a chance to hydrate. Because the attribute has been added before react has had a chance to hydrate, React reports a warning to the console `Warning: Extra attributes from the server: data-pt-script`. 
Adding `suppressHydrationWarning` to the script tag will cause React to ignore that warning.
=> suppressHydrationWarning

scripts/build-react.ts, src/lib/web-worker/init-web-worker.ts, src/react/forward.tsx, src/react/integration/facebook-pixel.tsx, src/react/integration/google-tag-manager.tsx, src/react/library.tsx, src/react/script.tsx, tsconfig.json
This PR fixes the typos present in `tsconfig.json` and other files which import from `integration` directory.
=> chore: fix typo in the module path

src/utils/copy-lib-files.ts
Otherwise when `utils/index.mjs` is imported we get the following error:
```
ERROR  __dirname is not defined
at libDirPath (node_modules/@builder.io/partytown/utils/index.mjs:16:20)
```
=> fix: polyfill __dirname in esm

src/integration/snippet.ts
This PR fixes the `Partytown` react component. The component uses the `partytownSnippet` function, which uses the props of the component to call `createSnippet`.
The problem here is that the `createSnippet` deletes a property from the props object, which is [immutable](https://stackoverflow.com/questions/47471131/why-are-react-props-immutable). This error was introduced at version 3.0.0.
This PR fixes the issue by deconstructing the prop without mutating it. This didn't fail on version 2.4 because the props were being spread in another object ([here](https://github.com/BuilderIO/partytown/blob/1cdf59a59ef9d39587ac7e1bec30091c189814ac/src/react/library.tsx#L22)), which allowed the properties to be deleted.
=> fix: prop deletion broke react snippet

tests/integrations/gtm/index.html
I assume that if the `url` need not to be reverse-proxied, the original `url` needs to be returned as shown in https://partytown.builder.io/proxying-requests
=> Return orignal `url` if reverse-proxy is not needed in `resolveUrl()`

docs/proxying-requests.md
Documents how you can work-around the need for a proxy by downloading and serving third-party JavaScript resources locally.
=> docs: Add "Serving Resources Locally" section

docs/proxying-requests.md
I errantly left off `type="text/partytown"` from the `<script>` tags
=> docs: Add `type="text/partytown"` to the `<script>` tags

docs/facebook-pixel.md, docs/proxying-requests.md, src/utils/api.md, src/utils/copy-lib-files.ts, src/utils/fs.ts, src/utils/index.ts, src/utils/rollup.ts, src/utils/vite.ts
Provides `rollupPartytownCopyLib()` and `vitePartytownCopyLib()` plugins to copy the lib directories to a destination.
=> feat: rollup/vite copylib plugin

src/lib/web-worker/worker-document.ts, tests/platform/document/document.spec.ts, tests/platform/document/index.html
This PR adds the [forms](https://developer.mozilla.org/en-US/docs/Web/API/Document/forms) property to the document object
=> Add forms property

src/lib/main/snippet.ts
Remove Script Length check to ensure service workers are always initialized regardless of whether any text/partytown scripts are present or not.
This is to ensure that we can handle pages which load text/partytown scripts async, which are sometimes loaded after the initial check for partytown is done.
=> fix: remove script length check when initializing service worker

docs/nuxt.md
it's important this tag is uppercase as it's a custom meta tag rather than the native html element
=> docs(nuxt): use capitalised script tag

docs/copy-library-files.md
A common use case for this is when you wish to move a set of fonts, installed through NPM, to your public directory with the copy command.
I google it for hours and I couldn't find a way of integrating **Partytown** in my `laravel mix bundler` which is built on top of webpack they provide a such fluent way to copy the `lib `to the public assets, i hope that will be helpful for developers who look for it in the future
=> Laravel mix Integration

tests/integrations/jquery/index.html, tests/integrations/jquery/standard.html
I don't think the content of jquery/standard.html should be GTM. 🤔
=> fix: Fixed incorrect content For jquery/standard.html

README.md
Added missing repo name in the `builder` link
=> fix (docs): builder link

src/lib/types.ts, src/lib/web-worker/worker-iframe.ts, src/lib/web-worker/worker-node.ts, tests/platform/iframe/iframe.spec.ts, tests/platform/iframe/index.html
This MR allows us to execute scripts from [Javascript URLs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void#javascript_uris)
=> Iframe Javascript URLs

src/lib/utils.ts
This is a solution for, and should close #97
Angular has zone.js and the constructor names cannot be fetched from there
=> GetConstructorName cannot handle Angular

src/lib/sandbox/main-register-window.ts, src/lib/types.ts, src/lib/web-worker/index.ts, src/lib/web-worker/worker-constants.ts, src/lib/web-worker/worker-location.ts, src/lib/web-worker/worker-window.ts, tests/platform/history/history.spec.ts, tests/platform/history/index.html
Hey I was investigating issue with GTM inside next.js app. I noticed that tag manager assigns custom pushState/replaceState to forward history changes on SPA. However, Partytown never forwards those calls to worker.
An issue describing this problem was already reported here: https://github.com/BuilderIO/partytown/issues/165
This MR fixes the problem.
=> Propagate pushState/replaceState inside worker

src/lib/utils.ts, src/lib/web-worker/worker-anchor.ts, tests/platform/anchor/anchor.spec.ts, tests/platform/anchor/index.html
I noticed that with current implementation of anchor property setter doesn't really work with properties other than `href`. Run this code inside Partytown to see what I'm talking about:
```js
a = document.createElement('a');
a.href = 'https://partytown.builder.io/?foo=bar'
a.search = '?x=y';
console.log(a.href);
// logs: https://partytown.builder.io/?https://partytown.builder.io/?x=y
// should be: https://partytown.builder.io/?x=y
a = document.createElement('a');
a.href = 'https://partytown.builder.io/?foo=bar'
a.host = 'foo.bar';
console.log(a.href);
// logs: https://https/?foo=bar
// should be: https://foo.bar/?foo=bar
```
This PR reimplements the setter.
=> fix: anchor property setter

src/lib/web-worker/worker-serialization.ts, tests/integrations/main-window-accessors/index.html, tests/integrations/main-window-accessors/main-window-accessors.spec.ts
I recently stumbled upon `mainWindowAccessors`. I thought it would be cool if this could forward function calls too.
The implementation appeared to be relatively easy - I just added `callMethod` inside `worker-serialization.ts`. I didn't find any downsides of my change yet, but I would like to see another opinion.
This change along with my other PR (https://github.com/BuilderIO/partytown/pull/172) allowed me to integrate GTM Tag Assistant with Partytown inside Next.js app (https://github.com/BuilderIO/partytown/issues/72).
https://user-images.githubusercontent.com/381865/169507409-3de028e4-cb19-4093-96d2-55a85a275faf.mp4
What you see on the video above is Tag Assistant communicating with GTM running inside Partytown. It requires Tag Assistant Companion browser plugin. Change in Partytown …
=> Add support for passing functions in `mainWindowAccessors`

src/lib/web-worker/worker-image.ts, tests/platform/image/image.spec.ts, tests/platform/image/index.html
I noticed that Partytown does not attach third-party cookies when fetching images. This breaks facebook pixel - take a look at the screen recording below.
On the left I have Facebook's 'Test events' tool. On the right NextJS app with Facebook Pixel added through GTM running within Partytown 😅 
https://user-images.githubusercontent.com/381865/169493259-26399c43-1c6c-45d5-ba3f-b8068c3881da.mp4
In addition to missing `credentials: 'include'`, I noticed that Image constructor never sets `src` attribute, I fixed it.
=> Include third-party cookies when fetching images

src/lib/sandbox/main-serialization.ts, src/lib/types.ts, src/lib/web-worker/worker-serialization.ts, tests/index.html, tests/platform/error/error.spec.ts, tests/platform/error/index.html
This MR adds support for forwarding errors to Partytown. I tested it with DataDog's RUM and it seems to be working just fine!
=> feat: serialize errors send to worker

src/lib/web-worker/index.ts
I found a bug in the way pushState is propagated inside worker - it's called with previous location.
=> fix: update location before calling pushState handlers

src/integration/api.md, src/lib/types.ts, src/lib/web-worker/worker-script.ts, tests/index.html, tests/integrations/load-scripts-on-main-thread/index.html, tests/integrations/load-scripts-on-main-thread/load-scripts-on-main-thread.spec.ts, tests/integrations/load-scripts-on-main-thread/test-script.js
Feature as requested by: #161
It was originally suggested that the configuration should look like this:
```js
<script>
partytown = {
loadWithPartytown: (url) => {
if (/* your own logic for what to load in partytown vs not */) return true;
return false;
}
}
</script>
```
I have created it as an array:
```js
/**
* This array can be used to filter which script are executed via
* Partytown and which you would like to execute on the main thread.
* 
* @example loadScriptsOnMainThread:['https://test.com/analytics.js']
* // Loads the `https://test.com/analytics.js` script on the main thread 
*/
<script>
partytown = {
loadScriptsOnMainThread: ['https://test.com/analytics.js']
}
</script>
```
This is because when the function gets serialized the function is a string and cannot execute.
If we wish …
=> feat: add configuration to run specific scripts on main thread

docs/configuration.md
The loadScriptsOnMainThread configuration has recently been merged in and needs to be documented on the site.
=> docs: add loadScriptsOnMainThread config to docs

src/lib/web-worker/worker-document.ts, tests/platform/document/document.spec.ts, tests/platform/document/index.html
I've got a script I'd like to run from Partytown that accesses `document.images` which currently returns `undefined` instead of the proper `HTMLCollection`. I've added support for `document.images` (following the implementation of `document.cookies` as an example). Happy to tweak this if this isn't quite right.
=> Added support for document.images

src/lib/web-worker/worker-exec.ts, tests/unit/worker-exec.spec.ts
This PR modifies the snippet used to wrap scripts with functions exposed via 'globalFns.' Previous implementations did not work properly when functions were declared within a 'try/catch' block, for example:
```html
<script type="text/partytown">
try {
function hello() {
console.log('hello world!');
}
} catch (err) {}
</script>
<script type="text/partytown">
if (hello) {
hello();
}
</script>
```
=> fix: expose global functions when they are wrapped with try/catch

docs/configuration.md, src/lib/types.ts, src/lib/web-worker/worker-node.ts, tests/integrations/load-scripts-on-main-thread/index.html, tests/integrations/load-scripts-on-main-thread/load-scripts-on-main-thread.spec.ts
This PR extends `loadScriptsOnMainThread` functionality to inline scripts. This modification is required to address a common scenario in which an inline script sets up the environment for another script loaded from the network.
Inline scripts are targeted using the `id` attribute.
Let's assume that the following snippet is a custom HTML tag in GTM:
```html
<script src="https://third-party-service-that-needs-main-thread.com/tracking.js" async></script>
<script id="third-party-service">
window._thirdParty = window._thirdParty || [];
</script>
```
Now, using the following configuration:
```jsx
<Partytown
loadScriptsOnMainThread={[
'https://third-party-service-that-needs-main-thread.com/tracking.js',
'third-party-service'
]}
...
```
both scripts will be executed on main thread, but I can …
=> feat: allow running specific inline scripts on main thread

docs/copy-library-files.md
I was testing this plugin implementation and I got an "Options should be array" error. After investigation I found that the webpack copy plugin docs are wrong.
See more here: https://github.com/webpack-contrib/copy-webpack-plugin/issues/455
=> Webpack copy plugin error fix

src/lib/sandbox/main-serialization.ts
=> Prevent serializer from calling `path` on `Event` object.

src/lib/types.ts, src/lib/web-worker/worker-proxy.ts
When experimenting with hooks, I found the context provided in `HookOptions` to be insufficient for some use cases. For example, I wanted to prevent a script from calling `alert()` by replacing the call with the construction of a `dialog` using an `apply` hook:
```html
<script>
var partytown = {
apply(opts) {
if (opts.name === 'alert') {
const doc = opts.window.document;
const dialog = doc.createElement('dialog');
dialog.open = true;
dialog.appendChild( doc.createTextNode(opts.args[0]) );
doc.body.appendChild(dialog);
return undefined;
}
return opts.continue;
},
};
</script>
```
I found this wasn't possible because the proxied DOM is not exposed to the hook (which I'm here accessing via `opts.window.document`). So this PR exposes the `window` as a property on `HookOptions`. 
Another use …
=> Include `instance` and `window` on `HookOptions`

src/lib/types.ts, src/lib/web-worker/worker-image.ts
In Meta Pixel they use Image for sending the analytics.
But the flow does not use the resolveUrl logic, which get's us CORS error.
fixed issue: https://github.com/BuilderIO/partytown/issues/306
=> resolving url for Image

docs/nextjs.md
Double quotes are needed, so npm install "@builder.io/partytown"
=> fix: Next.js NPM Install

src/lib/sandbox/main-serialization.ts
This fixes #284 and also fixes #313 and also fixes #178.
A previous PR (#269) tried checking if the object to serialize for the worker was an Event using `obj instanceof Event`. However, this was failing for some reason. I changed the check to use [`getConstructorName`](https://github.com/BuilderIO/partytown/blob/main/src/lib/utils.ts#L14-L26).
I did some brief testing on a Next app using the build output and the deprecation warning doesn't appear anymore.
=> Check for `Event` object with `getConstructorName` during worker serialization

tests/platform/image/image.spec.ts, tests/platform/image/index.html
As requested here:
https://github.com/BuilderIO/partytown/pull/307
Added a check that images requests goes through resolveUrl function
@adamdbradley
=> added a test for image resolveUrl

package.json
When using `moduleResolution="Node16"` inside `tsConfig`'s `compilerOptions` the types currently don't get resolved correctly.
The fix is it to specify the `types` property on all `exports` fields.
=> add support for `TypeScripts` `moduleResolution="Node16"`

src/lib/main/snippet.ts
It's very common for third party libraries to initialize with an embedded script that initializes a global variable only if it isn't already defined. For example, here is an excerpt from the Segment embed code:
```javascript
window.analytics=window.analytics||[];
```
If Partytown hasn't fully initialized before the fallback timeout is called, then these embedded scripts will run in the main thread but their global variable names will already be defined if a forwarding function was defined. This can prevent the proper initialization of these libraries in fallback mode. Continuing with the Segment example, if you configure Partytown with `forward: ['analytics.identify`]` then `window.analytics` will be an object rather than an array when the Segment embed code runs and the code will fail …
=> Clean up forwarded functions after timeout and fallback

docs/partytown-scripts.md
Quick fix for a typo on the partytown scripts docs page
=> Fix: correct typo in 'Partytown Scripts' section

docs/_table-of-contents.md, docs/index.md
Now that github is the more manageable place for partytown issues
=> Remove discord references in docs

docs/_table-of-contents.md
This PR updates the link to the Qwik integration documentation in the docs/_table-of-contents.md file.
- close #400 
The change is necessary to ensure users are directed to the correct documentation page for the Qwik integration.
- 1. One use case is when a user wants to learn more about the Qwik integration and clicks on the link in the table of contents.
- 2. Another use case is when a user is browsing the documentation and wants to navigate between different sections. The updated link ensures they end up at the right location.
=> docs(table-of-content): update qwik link

docs/integrations.md
The URL to Qwik is broken on this page and goes to a 404. This MR updates that URL to the correct URL.
Current user experience:
=> Update integrations.md with correct Qwik URL

docs/sveltekit.md
Changes:
- `onMount` should not be used. It's called on document load. For the GA example, that's too late
- write the scripts to SvelteKit's output directory rather than the user's source directory
- Remove the reverse proxying example. It's extremely confusing to show a reverse proxy with for GA because it conflicts with [the GTM docs](https://partytown.builder.io/google-tag-manager), which say a reverse proxy is not necessary
- Clarify that one step refers to `svelte-preprocess`, which is generally no longer used
=> docs: overhaul SvelteKit guide

docs/forwarding-events.md
The current page is quite confusing as it doesn't say where the JSON config goes. It sounds like it should go in a `partytown.json` or something. If I understood correctly from other pages then it goes in a `script` block which does not have `type="text/partytown"` and assigns it to a `partytown` variable.
=> docs: show full event forwarding example

docs/google-tag-manager.md
Two changes:
- Update GA section now that Universal Analytics is no longer collecting data
- Give a full GTM example that shows both an external script and inline config
=> docs: update Google Tag Manager page

src/react/snippet.tsx
Add an optional `nonce` prop to be applied to the script. Fixes https://github.com/BuilderIO/partytown/issues/299
Some users are using content security policies are required to append a `nonce` attribute to scripts, otherwise they won't be executed by the browser
=> feat: support for `nonce` prop

tests/platform/node-filter/index.html, tests/platform/node-filter/node-filter.spec.ts, tests/platform/tree-walker/index.html, tests/platform/tree-walker/tree-walker.spec.ts
This PR contains test cases for [NodeFilter](https://www.w3.org/TR/DOM-Level-2-Traversal-Range/traversal.html#Traversal-NodeFilter) API and [TreeWalker](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker) API. They are mainly for testing issues #253 and #254.
- `tests/platform/node-filter`: test case for NodeFilter
- `tests/platform/tree-walker`: test case for TreeWalker
```bash
npx playwright test tests/platform/node-filter --browser=chromium
npx playwright test tests/platform/tree-walker --browser=chromium
```
```bash
npm run serve
```
Then open the following pages in browser:
http://localhost:4000/tests/platform/node-filter/
http://localhost:4000/tests/platform/tree-walker/
=> test: Test cases for NodeFilter and TreeWalker

src/lib/main/snippet.ts, src/lib/types.ts, src/react/snippet.tsx
This commit updates the signature of the `PartytownConfig` interface to include
the `nonce` property. The `nonce` property can now be specified globally and will be
subsequently set on `script` elements created by Partytown.
=> feat: allow specifying `nonce` in global config

src/lib/main/snippet.ts
This commit sets style properties on the sandbox directly using the `style[property] = value` syntax. This method is allowed by CSP configurations. Previously, it was calling `sandbox.setAttribute('style', '...')`, which is often restricted because it involves setting inline styles via an attribute.
=> fix: set sandbox iframe styles directly through JavaScript

src/integration/snippet.ts
This PR fixes a bug that prevents some 3rd party scripts from loading in browsers that does not support service workers and atomics.
Partytown initializes all of the properties listed in the 'forwarded' array. However, at this point, it does not check to see if the browser supports the required features; this is done later. As a result, some third-party scripts may mistakenly perceive themselves as already loaded (for example FB pixel checks if the `fbq` property is present).
In my experience, the most common browser that does not support Partytown is... the iOS in-app browser! Users who click on Facebook ads see your website without Partytown loaded.
=> fix: exit early when both atomics and ServiceWorker are not supported

src/lib/sandbox/read-main-platform.ts, src/lib/service-worker/sync-create-messenger-sw.ts, tests/platform/klaviyo/current-script-src.js, tests/platform/klaviyo/document.spec.ts, tests/platform/klaviyo/index.html
After adding an example Klaviyo script tag, the Partytown workers fails to initialize because of the following error: 
Further debugging shows that the Klaviyo object (`window.klaviyo`) is the culprit of the non-serializable objects (below links are images):
[Analyzing Klaviyo object serializability](https://cdn.discordapp.com/attachments/1145098177427558410/1145098799996489788/image.png)
[Debug logs before initial `postMessage` call with the results of `readMainPlatform`](https://cdn.discordapp.com/attachments/1145098177427558410/1145098800495591595/image.png)
More information at the [following Loom recording](https://www.loom.com/share/66f906a3b23d4903a43dec4a68cf3943)
In the Loom there seems to be weird behavior with reloading with/without cache and with the "Update on reload" option …
=> Partytown worker failing to initialize after passing non-serializable objects to postMessage

src/lib/web-worker/worker-exec.ts, tests/unit/worker-exec.spec.ts
Better replaces `this` in third-party source code and avoids producing unrunnable code. 
It was more described in https://github.com/BuilderIO/partytown/issues/452
eg: `this` replacing regex is breaking some scripts 
- 1. (Google Analytics via Segment)
=> fix: impore how we replace `this` in third-party code`

docs/sveltekit.md, src/utils/rollup.ts
Simplifies setting up Partytown
Users shouldn't have to specify the output directory a second time on top of specifying it in Rollup. For SvelteKit the output directory is considered an internal implementation detail which makes having to specify it even a bit more surprising
=> feat: fallback to Rollup/Vite output directory

tests/platform/element-style/element-style.spec.ts
=> fix: playwright test

src/lib/web-worker/worker-exec.ts, tests/unit/worker-exec.spec.ts
This is follow up PR that cleans up code and adds tests
https://github.com/BuilderIO/partytown/pull/453/files
=> chore: cleanup and add tests

docs/sveltekit.md
- Remove an unnecessary step
- Put the optional step at the end
- Put the two steps editing the same file next to each other
Reviewing the table of contents in lines 7-10 will help understand this change
`svelte-preprocess` has been updated such that this option is no longer necessary. See https://github.com/sveltejs/svelte-preprocess/pull/622 for more details
=> docs: improve SvelteKit docs

src/lib/web-worker/worker-document.ts, tests/platform/window/index.html, tests/platform/window/window.spec.ts
`document.scripts` (or `window.document.scripts`) 
Accessing `document.scripts.length` triggers an error because `document.scripts` yields `undefined`. This issue arises from attempting to retrieve the length property of an undefined object, causing a code execution error in context of partytown workers.
Use case: we tried migrating Google publisher tag scripts into Partytown on our website (https://automobile.nau.ch/) and got following error:
It can be reproduced by running any code that accesses the properties of `document.scripts` (or window.document.scripts)
=> fix: add document.scripts & tests

docs/sveltekit.md
Setting `dataLayer.push` doesn't make sense until you have the Google Analytics script that uses it. Including it at this step could confuse users and make them think it's something everyone needs to do whether you use Google Analytics or not
=> docs: remove dangling code reference

src/lib/web-worker/worker-anchor.ts, tests/platform/anchor/anchor.spec.ts, tests/platform/anchor/index.html
An error is thrown when trying to access a property of an anchor element that hasn't been set an href. This PR fixes this issue handling the scenario and returning an appropriate value depending on the property accessed.
This is how the error looks like:
=> fix: solve error with anchor without href

docs/facebook-pixel.md
- [✖️] Feature / enhancement
- [✖️] Bug
- [✅] Docs / tests
Updated code example snippet and corrected an issue in code syntax.
N/A
- [ N/A] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/partytown/blob/main/CONTRIBUTING.md)
- [✅] I have performed a self-review of my own code
- [✅] I have made corresponding changes to the documentation
- [N/A] Added new tests to cover the fix / functionality
=> docs: fix typo in facebook-pixel page

src/lib/web-worker/worker-image.ts, tests/platform/image/image.spec.ts, tests/platform/image/index.html
removeEventListener is missing on internal Image implementation, which can cause errors in some scenarios.
Well, it's part of the spec, so it would be great if Partytown correctly handles this.
=> feat: add image.removeEventListener implementation

src/lib/web-worker/worker-window.ts, tests/platform/event/event.spec.ts, tests/platform/event/index.html
This will update addEventListener method to always have correct  `this` value, even when it's called without context.
While updating OneTrust service integration on our website to use Partytown, I've noticed that they are [using](https://cdn.cookielaw.org/scripttemplates/otSDKStub.js) addEventListener alongside window.attachEvent to support older versions of browsers.
The problem with the code they've written is that when addEventListener is called inside of WebWorker's addEventListener it has no context (`this === undefined`) and we get an error
Looks like we can easily update Partytown to support such cases by simply updating addEventListener to use arrow function (which preserves context).
P.S. `postMessage` method in this class has same problem, but I'm not sure whether we need to …
=> fix: preserve this inside addEventListener

package.json
=> fix(ci): add packageManager property

docs/forwarding-events.md, src/lib/main/snippet.ts, src/lib/sandbox/main-forward-trigger.ts, src/lib/types.ts, src/lib/utils.ts, tests/integrations/event-forwarding/event-forwarding.spec.ts, tests/integrations/event-forwarding/index.html, tests/integrations/gtm/gtm.spec.ts, tests/integrations/gtm/preserve-behavior.html, tests/integrations/gtm/standard.html
This PR adds the ability to preserve the behavior of forwarded functions. This comes in candy for some scenarios, for example, some third parties integrations that monitor the global `dataLayer` array in order to work. When GA is handled by partytown the array will be empty, this new functionality allows to keep the events there.
Even if the motivation for this is GA and the dataLayer array, this would work for any other forwarded method, as it makes the trick including a call to the original method in the patched version (in fact, in the tests added there is a case where the forwarded method is `unshift` instead of `push`).
If you want to enable this new setting, you would do it like this:
`forward: ['simpleProperty', ['dataLayer.push', { preserveBehavior: true }]],`
I also contemplated …
=> feat: improve forwarding-events with `preserveBehavior`

src/lib/web-worker/worker-navigator.ts, tests/platform/navigator/index.html, tests/platform/navigator/navigator.spec.ts
Some third party integration we have tries to access a navigator's property that is defined in the top-level navigator ([Navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator)) instance but not in the worker navigator ([WorkerNavigator](https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator)).
In my case the properties are `javaEnabled` and `cookieEnabled`.
This should fix #414 and  #270
=> feat: access missing navigator properties

.gitignore, scripts/build-integration.ts, src/integration/index.ts, src/integration/snippet.ts, src/lib/sandbox/read-main-platform.ts, src/lib/types.ts, src/lib/utils.ts, src/lib/web-worker/init-web-worker.ts, src/lib/web-worker/worker-node.ts, src/lib/web-worker/worker-script.ts, tests/integrations/load-scripts-on-main-thread/background-test-script.js, tests/integrations/load-scripts-on-main-thread/load-scripts-on-main-thread.spec.ts, tests/integrations/load-scripts-on-main-thread/regex-test-script.js, tests/integrations/load-scripts-on-main-thread/snippet.html, tests/integrations/load-scripts-on-main-thread/test-script.js, tests/integrations/load-scripts-on-main-thread/wait-for-class.js, tests/unit/utils.ts
This PR fixes two issues with loadScriptsOnMainThread:
- When using a regexp in loadScriptsOnMainThread all scripts will be executed in the main thread, even if their url doesn't match the regexp.
- If a string is used and it includes some characters reserved by regexp (such as interrogation marks), even if the script src seems to match, the script won't be executed in the main thread.
You can check the issue if you execute the new tests added (checking out the first commit of the PR) without the fix included in the PR (second commit).
I added new tests in `tests/integrations/load-scripts-on-main-thread` to display whether the scripts in the page have been executed on the main thread or in the background. In addition I added a new script, `background-test-script.js` that should be …
=> fix: loadScriptsOnMainThread breaks when using a regexp

docs/sveltekit.md
=> docs(SvelteKit): remove unused import

docs/_table-of-contents.md, docs/integrations.md, docs/solid.md
=> docs: add Solid integration

src/lib/log.ts, src/lib/sandbox/read-main-platform.ts, src/lib/types.ts, src/lib/web-worker/init-web-worker.ts, src/lib/web-worker/worker-constants.ts, src/lib/web-worker/worker-document.ts, src/lib/web-worker/worker-storage.ts, src/lib/web-worker/worker-window.ts, tests/platform/storage/storage-access.html, tests/platform/storage/storage-access.spec.ts
In the current implementation, we cache both storages (localStorage and sessionStorage) at the moment of worker creation. Although this could be considered as performance optimization, it leads to the implementation inconsistency:
- Storage data leaks into 3rd party script
- Storages easily go out of sync as there is no proper synchronization with main window setup.
- One can not override the storage access easily.
For the latter point, this means we can not take on the methods like `localStorage.getItem()` in the Partytown proxy methods (specifically in `apply`). Hence there is no way to shield the storage data from 3rd party scripts.
In this commit we fully rely on the storage values the main window sends into the worker. As the result, we can always receive relevant value and also can …
=> fix: proxy localStorage and sessionStorage (closes #293)

docs/_table-of-contents.md, docs/shopify-os2.md, src/lib/sandbox/read-main-platform.ts, src/lib/web-worker/init-web-worker.ts, src/lib/web-worker/worker-storage.ts
Documentation for the Shopify OS 2.0 integration.
- For all who want to use Partytown within a Shopify OS 2.0 theme.
=> docs: Add Shopify OS 2.0 integration page

src/lib/types.ts, src/lib/web-worker/init-web-worker.ts, src/lib/web-worker/worker-exec.ts, src/lib/web-worker/worker-navigator.ts, tests/platform/navigator/index.html, tests/platform/navigator/navigator.spec.ts
This change introduces a new hook called `resolveSendBeaconRequestParameters` on the `PartytownConfig`. This enables consumers to modify a subset of the `RequestInit ` parameters being used by the fetch request that polyfills the navigator.sendBeacon API in the worker context, e.g. setting keepalive: false.
An alternative solution would be to just set `keepalive: false` as default. But as I am not aware of the reasoning behind your defaults, I thought it's a good idea to make it user configurable.
The current implementation of the `sendBeacon` has static values for the `RequestInit` parameters it uses to initialize the post request. The goal is to make those parameters being user configurable. 
I am not 100% sure why you have chosen to go with those default values, but I've notice that …
=> feat: add sendBeacon request parameters hook

docs/sveltekit.md
The Google Tag Manager example for SvelteKit is wrong, when trying to use `gtag` it throws a `gtag is not defined` error. The reason it fails (not explicitly declaring the function as global) also applies to other scripts.
* Using Google Tag Manager correctly on SvelteKit.
* Making global functions and variables available
=> docs(SvelteKit): fix Google Tag Manager example

src/lib/web-worker/worker-constants.ts, src/lib/web-worker/worker-script.ts, tests/integrations/load-scripts-on-main-thread/index.html, tests/integrations/load-scripts-on-main-thread/load-scripts-on-main-thread.spec.ts, tests/integrations/load-scripts-on-main-thread/snippet.html, tests/platform/script/index.html, tests/platform/script/script.spec.ts
There are some bugs in Partytown's `<script>` implementation that were reported looong time ago along with MRs that were supposed to fix those bugs, unfortunately none was merged yet:
- https://github.com/BuilderIO/partytown/pull/234
- https://github.com/BuilderIO/partytown/pull/399
In summary:
Take a look at this code:
```
div = document.createElement('div');
div.innerHTML = '<script>console.log(42);</script>';
console.log(div.firstChild.innerHTML);
```
It should log the content of the script. Unfortunately when run inside Partytown it returns empty string.
```
script = document.createElement('script');
script.text = 'console.log(42);';
```
GTM uses this internally when setting content of scripts added as custom HTML tags.
I use GTM through Partytown. However I want to have some custom …
=> fix: update worker-script innerHTML implementation

src/lib/main/snippet.ts, src/lib/sandbox/read-main-platform.ts, src/lib/service-worker/fetch.ts, src/lib/types.ts, src/lib/web-worker/init-web-worker.ts, src/lib/web-worker/worker-proxy.ts, tests/index.html, tests/platform/multiple-tabs/index.html, tests/platform/multiple-tabs/multiple-tabs.spec.ts
For some reason service worker is set to send messages to the latest client only. This leads to `error finding instance`, when user opens several tabs in the browser and switches not to the latest tab. More description [here](https://github.com/BuilderIO/partytown/issues/202).
Open several tabs in the browser with the same site. Partytown should run with service worker, not Atomics.
Switch to the first tab. Now anytime web worker tries to send anything to the main thread, you'll get `error finding instance`. The problem is in below code, where service worker is set to send messages to the latest tab only.
```
const sendMessageToSandboxFromServiceWorker = (accessReq: MainAccessRequest) =>
new Promise<MainAccessResponse>(async (resolve) => {
const clients = await (self as any as …
```
=> fix: service worker communicates with the latest client only

docs/forwarding-events.md, docs/google-tag-manager.md
Copy information about explicitly adding functions to window from SvelteKit docs.
This is related to all frameworks
=> docs: Copy window example from SvelteKit implementation docs

docs/sveltekit.md
Fixing docs for SvelteKit. Static folder is for "any static assets that should be served as-is." 
https://kit.svelte.dev/docs/project-structure#project-files-static
=> docs: change SvelteKit section

src/lib/web-worker/worker-iframe.ts, src/lib/web-worker/worker-storage.ts, src/lib/web-worker/worker-window.ts, tests/platform/iframe/cookie.html, tests/platform/iframe/iframe-cookie-localstorage.spec.ts, tests/platform/iframe/index-cookie-localstorage.html, tests/platform/iframe/localstorage.html
Bug: Unable to get/set localStorage/cookies in a same-origin iframe created with Partytown.
Expected: Able to get/set localStorage/cookies in a same-origin iframe created with Partytown.
Fix: Set isSameOrigin after iframe src is set
"Partytown unable to get cross-origin localStorage" warning from Pinterest tracking pixel even though iframe src `https://ct.pinterest.com/ct.html` is proxied.
=> fix: Same-origin iframe set/get cookie/localStorage bug

.github/workflows/ci.yml, .github/workflows/linter.yml, docs/angular.md, docs/astro.md, docs/gatsby.md, docs/nextjs.md, docs/nuxt.md, docs/react.md, docs/remix.md, docs/shopify-hydrogen.md, docs/solid.md
While browsing the docs I noticed that the installation commands were not consistent through the "Integrations" section. Some pages say to use NPM, some Yarn, some both...one page even had quotes around the package name which is redundant.
=> docs: making install commands consistent

.github/workflows/ci.yml, .github/workflows/linter.yml
It seems pnpm installation currently not works:
https://github.com/BuilderIO/partytown/actions/runs/11243169210/job/31258440384?pr=631
v2 not working anymore:
https://github.com/pnpm/action-setup?tab=readme-ov-file#warning-upgrade-from-v2
=> ci: upgrade pnpm

src/lib/web-worker/worker-window.ts, tests/integrations/clarity/index.html
This PR is a copy from https://github.com/BuilderIO/partytown/pull/614 that PR should go in because third-parties like clarity are still broken
Include polyfill for CSSMediaRule (used by hubspot tracking js)
error when using clarity:
1. Use Case:
Hubspot references CSSMediaRule in their JS and it is currently failing because it doesn't exist in worker context.
We already have the polyfill for CSSStyleSheet and CSSMediaRule has the same interface so the same polyfill should work!
=> fix: (worker-window): polyfill CSSMediaRule - copy from the PR #614

docs/nextjs.md
Added clarification that the `worker` strategy is currently unsupported with the next.js `app` directory.
It's not currently clear that partytown won't work with the next.js `app` directory
=> docs: clarified that the `worker` strategy is not supported with app directory

docs/sveltekit.md
I'd prefer not to have my real web property ID listed there. Looks like I accidentally included it in an earlier docs change :laughing: 
So other people don't accidentally send their traffic to my analytics account
=> docs: use dummy web property ID

docs/facebook-pixel.md
Added reverse proxy handler example for Facebook Pixel integration and updated documentation.
=> docs: Add example reverse proxy handler for Facebook Pixel

docs/src/routes/copy-library-files/index.mdx
If I try to copy the library files by following the instructions in the [docs](https://partytown.builder.io/copy-library-files), then [Deno](https://deno.com/) throws the following error:
```sh
deno task partytown
Task partytown partytown copylib public/~partytown
error: Error parsing script 'partytown'.
Caused by:
Unexpected character.
~partytown
~
``` 
Deno supports running npm scripts natively with the [deno task](https://docs.deno.com/runtime/reference/cli/task_runner/) subcommand. But in the case of Partytown, the `~` in the default path is causing a [tilde expansion](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html), erroring out Deno CLI.
To fix this, you can pass the path in [single quotes](https://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html …
=> fix(docs): escape tilde expansion in copy task command instruction

package.json, pnpm-lock.yaml, src/lib/types.ts, src/lib/web-worker/worker-window.ts
Update the prettier dependency. 
Currently `npm install` on `main` gives these errors
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @qwik.dev/partytown@0.11.0
npm ERR! Found: prettier@2.8.8
npm ERR! node_modules/prettier
npm ERR!   dev prettier@"^2.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer prettier@"^3.0.0" from pretty-quick@4.1.1
npm ERR! node_modules/pretty-quick
npm ERR!   dev pretty-quick@"^4.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```
I've simply updated the prettier …
=> chore: update prettier

.changeset/chilly-eggs-yawn.md, src/lib/web-worker/worker-document.ts
Clarity is trying to access `document.adoptedStyleSheets` in the worker, which returns an array of strings:
#666 
- 1. When accessing document.adoptedStyleSheets, should get the actual value
I have checked the http://localhost:4000/tests/integrations/clarity/ test before and after the fix.
I can confirm that before the fix, the error was present (after some time):
And after the fix, Clarity seems to work and no error was present (even after some time spent on the page):
=> fix: Add adoptedStyleSheets.get() to patched `document` in worker.
