QwikDev/partytown

- .gitattributes
https://twitter.com/adamdbradley/status/1443224050319433738
> Skip integrations from the repo language detection

- src/lib/sandbox/on-messenge-from-worker.ts
- src/lib/types.ts
Just a small change to add labels to currently in used tuple times to
better convey the intent.
Remove superfluous type casts, they were already the correct type.
You can see this as a metadata in the LSP.
> feat: Add tuple labels for clarity

- tests/index.html
- tests/integrations/adobe-launch/AppMeasurement.min.js
- tests/integrations/adobe-launch/adobe-launch.spec.ts
- tests/integrations/adobe-launch/index.html
- tests/integrations/adobe-launch/launch-d4935864d5f5.min.js
- tests/integrations/adobe-launch/standard.html
> test: adobe launch

- src/lib/web-worker/worker-form.ts
- src/lib/web-worker/worker-window.ts
- tests/index.html
- tests/platform/form/form.spec.ts
- tests/platform/form/index.html
This PR patches [HTMLFormElement.elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/elements)
> Form elements

- docs/nextjs.md
- Script syntax typo  fix in nextjs integration docs
> Fix typo errors nextjs integration docs

- docs/astro.md
Updates Astro × Partytown docs to feature the new `astro add partytown` command. Pretty easy!
> Update astro docs

- docs/how-does-partytown-work.md
Makes the description of serialization a little simpler/more straightforward.
> Update note on Serialization

- docs/_table-of-contents.md
- docs/angular.md
This PR contains a draft for the docs on how to setup partytown in an angular application
> docs: angular partytown docs init

- src/lib/web-worker/worker-image.ts
- tests/platform/image/image.spec.ts
- tests/platform/image/index.html
Fixes issue with `twitter` ads accessing style on image.
https://github.com/BuilderIO/partytown/issues/215
> fix(partytown): add style to image class

- .gitignore
- src/lib/web-worker/worker-serialization.ts
- src/lib/web-worker/worker-window.ts
- tests/index.html
- tests/platform/node-list/index.html
- tests/platform/node-list/node-list.spec.ts
Closes: https://github.com/BuilderIO/partytown/issues/271
- Add `NodeList` to window using `defineConstructorName` similair to `Node` in [worker-node.ts](https://github.com/itxch/partytown/blob/5e8955c489b9defa1acde0a44f1cce21a7bdf43f/src/lib/web-worker/worker-node.ts#L24)
- Added some tests around NodeList
- Add `the .idea folder to gitignore
> fix: NodeList is not defined on window

- docs/distribution.md
- docs/how-does-partytown-work.md
I found and fixed 2 small typos in the docs
> Fixed 2 typos in docs

- docs/getting-started.md
cf. https://developer.wordpress.org/reference/functions/capital_p_dangit/
> Fix capitalization of WordPress

- docs/copy-library-files.md
Update the sample code as per copy webpack plugin docs -> https://v4.webpack.js.org/plugins/copy-webpack-plugin/
> Updated weback copy plugin example code

- docs/_table-of-contents.md
- docs/integrations.md
- docs/sveltekit.md
basic docs, credit due to https://monogram.io/blog/add-partytown-to-svelte
> add sveltekit docs

- docs/_table-of-contents.md
- docs/nextjs.md
As pointed out by @leerob on the shared Builder/Vercel Slack channel - I fixed the link and edited the docs.
@adamdbradley - LMK what you think and if you want me to send you the chat.
> fix: Update Next.js docs

- docs/atomics.md
> Grammar nitpick

- docs/common-services.md
added mixpanel analytics entry as part of common services
> updated common services for mixpanel analytics

- docs/common-services.md
Apologies for such a minor change. I'm not a grammar N--member of the Alt-Write, I swear.
> Corrected Mixpanel typo in common-services.md

- src/lib/web-worker/worker-navigator.ts
- tests/platform/navigator/index.html
- tests/platform/navigator/navigator.spec.ts
This will fix https://github.com/BuilderIO/partytown/issues/378
> Fix navigator

- docs/trade-offs.md
> docs: fix a typo for trade-off

- package.json
> chore: update node version in package.json

- .github/workflows/pr.yml
- pnpm-lock.yaml
> chore: add PR title check

- docs/integrations.md
Use new issue link instead of Discord.
> docs: Update integrations.md

- src/lib/sandbox/main-access-handler.ts
- src/lib/web-worker/worker-constructors.ts
- src/lib/web-worker/worker-navigator.ts
- src/lib/web-worker/worker-serialization.ts
- src/lib/web-worker/worker-window.ts
- src/utils/rollup.ts
> chore: linter 🧽

- src/integration/api.md
- src/utils/api.md
> chore: update api md

- .github/workflows/linter.yml
- .github/workflows/pr.yml
- package.json
> chore: improve GH workflows

- tests/platform/iframe/iframe2.spec.ts
- tests/unit/utils.ts
> chore: skip flaky test

- src/integration/api.md
> chore: align api.md

- src/lib/types.ts
> chore: add missing tags

- docs/sveltekit.md
> fix: improve SvelteKit section

- .github/workflows/ci.yml
- .github/workflows/linter.yml
> chore: bump GH actions

- src/integration/api.md
> docs: add new PartytownConfig props

- docs/remix.md
> docs: update remix guide

- docs/magento2.md
Issue #527
Documentation on the integration module for Magento 2. https://github.com/rostilos/perspective-partytown
> docs: add integration module for Magento 2

- tests/integrations/gtm/gtm.spec.ts
> test: skip flaky test

- docs/site/package.json
> chore: freeze docs deps

- docs/src/routes/trade-offs/index.mdx
Tiny grammar fix, nothing crazy. See diff for changes.
N/A
> fix(docs): small typo in docs for trade-offs
